sudo: false
cache:
  directories:
  - node_modules
language: node_js
node_js:
- '0.12'
before_install: npm install -g grunt-cli
after_success: grunt travis
deploy:
  provider: npm
  email: ag-hostmaster+npm@appgyver.com
  on:
    tags: true
    repo: AppGyver/ag-relation-resolver
  api_key:
    secure: llEVVQ6Az33Ni1/dIQpc8L6cpsUh+5DSSUsTK4RIMHnC7MsHoFT48Li+UOXRp4/bNHPE9vKyh9N8LVO53KKMDE0ybCK5r+hHnV7+cU6EL5A4XGThBw1iw7NN0tvzPwtiq2ufFxyxK3iYaCJAWrxNjFs5ntDuNtSpYKjUKwAddD48eS9x6byc5NUGFJfLEZZwCm+T4gQGwmK7SXPqlbz45gKd0HeIGTYDs0HC1tqMlpC0FsM8zoAW5eyoksXg4st9yT7qRwsYljVvJvMv8E1eM6LTVmt2nkQptavF4OsUlJ033jbTg7EDC9hZXbCzXd2Y3lnTcfRHKNSWy/hh8SxrcbrtfYvAjLi1GSLVdCw3igF3Sv3y8XQGxjec8KQhlld7ZXolerBAV/ncn1BD/uZae53ek30gQxGWhNzGj+sXzkEgsq5WaTNVtVLPYX85j85ajEdrTS6am0PygtE69hlOrldrw5zD2iXaEwvio+4EQ+mQrPtvmK+6p4y58HdKulEzdKonF7nkh2HxhCaW5kc7EX+7bjESBXTIfvGFA6sqenw0JbRlD5O6YAMZ6DRXkevKND22mrkEYtaYegUy077f1Vse8L8L0349vVnWUzQmaxWXMT6266uVnCsFt8TCmW4uzhI3pdutm3YJzL/1EPBDG0E8nX0AKPt1KQ3viu49NzE=
env:
  global:
    secure: YUtEPMKKXTGSBHbg/JDv+euYoaAl0wjxQrjUzwljYbVs9PC1dy9I5373cZFEQwqrAiHYXDgrr94IQG658Gk1+Yz218g+ZoJvZBb/kbG44lkwvTgg5xpTkvwh6HM9joF0h9alD7JSMYRXecnjQXleALmJOcbuw9E++hft7CgKRbLqGkP7uzdvQk/l7UO8TbIg6Uf5URUoh1nXzxpWqfiP3PA6HyQObWj7ODn6w0l9bZhSr+R141illY/cCVXQDFszM+48dgkAjlMUK40HhWq6Z3wXcz5W+nmNWnRxLL5WN+OXvAf2Jsjuz/TM6fXeNb+P/ypK1VaxZvn2JHfoO06TY3BaqOaRIMtReE4JnyIj5quu45SSxZLGsgnTOQp7OHTd9Y71leQAsC3VaJa+6IyVhdEnIqwJQpcW9Uh++V3wbCQW5YtN4thcVSCADtcVhfLV4jakJbcNZXU9W7Vg+Vlky5DMqMcEU2Uz+FO/DRpxTB/Za61qxaM7ci69UvSruMuQu7uV4mQ36GHaIVNbOx7g6nkwI0QHsz3S08L2HVVcxyP4ZjgYpoD+SjoLwVqEzXI8h1ZqFSpF4Jb7BsU3Qy8EFx+6/PyhEI9RQAvXNMuC5301sHzCfKJ2NTyHThjexg+5CNY63wL28nKTxFdEi0c3F73nfx+iUlS24xYx3fKbXi0=
